### PR TITLE
Add watch as a dotnet option

### PR DESCRIPTION
**Pull request by Cliffback**
Added watch as an option for the C# / .NET compiler, as I have use for it myself.

> dotnet watch - Restarts or [hot reloads](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch#hot-reload) the specified application, or runs a specified dotnet command, when changes in source code are detected.

### CODE REVIEW

**Comment by Zeioth** [comment]
Seems reasonable to me. I've documented myself on the command and read your PR. 

But while testing it for some reason, even though I can run `dotnet run` correctly, the command `dontnet watch` fail on the the `project.csproj` of [our example csharp dotnet project](https://github.com/Zeioth/compiler.nvim/blob/main/tests/examples/languages/cs/build-dotnet/project.csproj).

screenshot_2024-02-09_15-28-42_375920882

Give me some time and see what's the issue so I can actually test it.

**Comment by Cliffback** [comment]
Thanks for considering the PR. 

That's curious. Just tested it with the example project, and ran fine for me.
Screenshot 2024-02-09 at 15 37 13

Did a search, and it seems that it requires aspnet-runtime to be installed, try `dotnet --list-runtimes` and see if you have it.

[https://stackoverflow.com/questions/74508499/dotnet-watch-no-frameworks-found
](https://stackoverflow.com/questions/74508499/dotnet-watch-no-frameworks-found
)

On my system: 
```
Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

If this is the case, I can either change the description to something like "requires AspNetCore", or add a check to only show the option if AspNetCore is installed?

**Comment by Zeioth** [comment]
Ok that works. For some stupid reason the dotnet command `dotnet watch` seems to require the system dependency `aspnet-runtime-bin` (arch).

This is a tricky one because different distros will likely package dotnet in a different way. So I'm just gonna comment it on the [+info](https://github.com/Zeioth/compiler.nvim/wiki/cs-compiler) section of C# for now.

screenshot_2024-02-09_16-27-00_659486763

Your PR works indeed elegantly out of the box so I'm gonna merge it.

**Comment by Zeioth** [comment]
Thank you so much for submitting it!!

**Comment by Cliffback** [comment]
Happy to help!

**Pull request merged**
