### PR TITLE
refactor: use open_output component instead of OverseerOpen

### LINKED ISSUE #27: Can we jump to the task output by default?
First of all, thank you so much for an awesome plugin!

I'd like to build and run and have the active Overseer item automatically be the task output without needing to navigate to it manually.

CleanShot 2024-02-02 at 21 22 15@2x

See the attached video to see what I mean: https://github.com/Zeioth/compiler.nvim/assets/37928/ff4a9890-de92-4bb7-8dd0-e412494c5210

### PR DESCRIPTION
**Pull request by stevearc**
A demonstration of how the new `open_output` component can be used to fix #27. If you like this approach, these changes will need to be replicated across all the other supported languages.

I'm not sure how you want the code formatted. My stylua (v0.20.0) throws an error that `remove_trailing_separators` is an unknown field.

### CODE REVIEW

**Comment by Zeioth** [comment]
I've tested this snippet, but it doesn't solve it. What we want to achieve is to display the children before the parent. 

As you can achieve in my PR just by setting the option `group_position = "bottom"`.

**Comment by stevearc** [comment]
Am I misreading this somehow?

> I'd like to build and run and have the active Overseer item automatically be the task output without needing to navigate to it manually.

Isn't that exactly what this does? I don't see anything about the ordering of the tasks. I understand that reordering the tasks would be one way to achieve this, but I think it makes the task list harder to parse, which is why I was trying to find different solutions. Have I misinterpreted what the issue is?

**Comment by Zeioth** [comment]
@stevearc I think we are talking about different stuff. I've recorded a video so I can show clearly what we are trying to achieve through my PRs:

* https://www.youtube.com/watch?v=Xh6PAsV6Og8

And another video testing your PR

* https://www.youtube.com/watch?v=8lHSEm6om7o

**Comment by stevearc** [comment]
Okay I think I know where the disconnect is. The things we are aligned on:
- When overseer runs an orchestrator task, it orders the orchestrator task visually above its subtasks.
- When the overseer task list is opened, it by default displays the output from the top task.
- The issue is that compiler.nvim uses orchestrator tasks, so when a task is started and the overseer list is opened, the output window shows the output from the orchestrator task which does not have the actual output from the run.
- The PR you sent allows for reordering the tasks so that the orchestrator task is on the bottom. This would fix the problem of the default output window not showing what you want, but I believe adds visual confusion.

The disconnect is that you don't see how this PR addresses the issue of showing the relevant output without reordering the tasks. I'm not sure what you're seeing because the videos you recorded seem to be static images, so it's possible that this produces different behavior on your computer (if so, that is a bug. This is possible because I did just find and fix a race condition). Here's what I see.

Using main branch of compiler.nvim and overseer.nvim:
Screenshot 2024-06-05 at 3 38 47 PM
This exhibits the issue where the output window in the lower right is showing the output of the orchestrator task, not the subtask.

Using this PR of compiler.nvim and the main branch of overseer.nvim:
Screenshot 2024-06-05 at 3 39 22 PM

As you can see the output window in the lower right is showing the output of the subtask. This is why I think it is solving the issue, even though the tasks remain in the same order.

**Comment by Zeioth** [comment]
Thank you @stevearc I see what you mean in the screenshot. It works different than my PR but achieves the same result by displaying the first children by default.

This is indeed the behavior we want to achieve thank you so much.

**Comment by Zeioth** [comment]
It wouldn't probably hurt making this the default behavior btw, as the task is the information the user wants too see anyway.

**Comment by Zeioth** [comment]
Merged as reference. Adding it to all the 22+ backends next.

**Pull request merged**
